// <auto-generated />
using System;
using Contact_Microservice.DataAccess.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Contact_Microservice.Migrations
{
    [DbContext(typeof(PgDbContext))]
    [Migration("20221009165321_contactpg_init")]
    partial class contactpg_init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Contact_Microservice.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContactType")
                        .HasColumnType("integer");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PersonUID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonUID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ed8eebe4-c077-463a-b0a8-1a744465c065"),
                            ContactType = 3,
                            Contents = "antalya",
                            PersonUID = new Guid("866c2580-7505-417e-8b2d-89be6d304335")
                        },
                        new
                        {
                            Id = new Guid("39192dbb-e8d1-4f61-abe1-5fa536704770"),
                            ContactType = 3,
                            Contents = "antalya",
                            PersonUID = new Guid("b58041ac-5714-4c93-98d5-a981f4754eed")
                        },
                        new
                        {
                            Id = new Guid("6fab9285-ecf3-400a-8bef-f3ddf83b1f5c"),
                            ContactType = 3,
                            Contents = "antalya",
                            PersonUID = new Guid("c7c24bf5-1097-4825-90c1-2f4233a3a2ce")
                        },
                        new
                        {
                            Id = new Guid("144fa168-5c07-46c1-a4ad-6890a99df997"),
                            ContactType = 3,
                            Contents = "izmir",
                            PersonUID = new Guid("c026ed21-910a-4c55-9135-41a20e65dc07")
                        },
                        new
                        {
                            Id = new Guid("2abae796-fd5b-49b7-aa19-7311f4f1c2de"),
                            ContactType = 3,
                            Contents = "izmir",
                            PersonUID = new Guid("023e1635-8be6-45cc-ad7d-2800a3b679bc")
                        },
                        new
                        {
                            Id = new Guid("aa6da8ad-df16-4a59-a3f0-c215e1ef238a"),
                            ContactType = 3,
                            Contents = "izmir",
                            PersonUID = new Guid("550ac5d8-5c79-4ab7-ad05-38f2ae7916b0")
                        },
                        new
                        {
                            Id = new Guid("22304ec0-794e-439b-9550-cd2a9f5afd0d"),
                            ContactType = 3,
                            Contents = "urfa",
                            PersonUID = new Guid("bdc3f868-7ed1-4db0-ae35-9a7283bc26ce")
                        },
                        new
                        {
                            Id = new Guid("80065b7f-b588-4b0e-92f3-fe9c91af2b39"),
                            ContactType = 3,
                            Contents = "urfa",
                            PersonUID = new Guid("1f410483-38c3-48df-9a99-76dbb2bf0d1a")
                        },
                        new
                        {
                            Id = new Guid("7e6fd57c-4608-4f0a-a44a-92280b2ce3be"),
                            ContactType = 3,
                            Contents = "urfa",
                            PersonUID = new Guid("409ba2b3-10a4-44eb-9193-f43d777b1e30")
                        });
                });

            modelBuilder.Entity("Contact_Microservice.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("866c2580-7505-417e-8b2d-89be6d304335"),
                            Company = "Sanatcı a.ş",
                            Name = "Levent",
                            SurName = "Yüksel"
                        },
                        new
                        {
                            Id = new Guid("b58041ac-5714-4c93-98d5-a981f4754eed"),
                            Company = "Futbol a.ş",
                            Name = "Burak",
                            SurName = "Yılmaz"
                        },
                        new
                        {
                            Id = new Guid("c7c24bf5-1097-4825-90c1-2f4233a3a2ce"),
                            Company = "Oyuncu a.ş",
                            Name = "Mehmet",
                            SurName = "Özgür"
                        },
                        new
                        {
                            Id = new Guid("c026ed21-910a-4c55-9135-41a20e65dc07"),
                            Company = "Oyuncu a.ş",
                            Name = "Elçin",
                            SurName = "Sangu"
                        },
                        new
                        {
                            Id = new Guid("023e1635-8be6-45cc-ad7d-2800a3b679bc"),
                            Company = "Oyuncu a.ş",
                            Name = "Selin",
                            SurName = "Şekerci"
                        },
                        new
                        {
                            Id = new Guid("550ac5d8-5c79-4ab7-ad05-38f2ae7916b0"),
                            Company = "Oyuncu a.ş",
                            Name = "Ece",
                            SurName = "Uslu"
                        },
                        new
                        {
                            Id = new Guid("bdc3f868-7ed1-4db0-ae35-9a7283bc26ce"),
                            Company = "Şarkıcı a.ş",
                            Name = "İbrahim",
                            SurName = "Tatlıses"
                        },
                        new
                        {
                            Id = new Guid("1f410483-38c3-48df-9a99-76dbb2bf0d1a"),
                            Company = "Şarkıcı a.ş",
                            Name = "Müslüm",
                            SurName = "Gürses"
                        },
                        new
                        {
                            Id = new Guid("409ba2b3-10a4-44eb-9193-f43d777b1e30"),
                            Company = "Şarkıcı a.ş",
                            Name = "Mahmut",
                            SurName = "Tuncer"
                        });
                });

            modelBuilder.Entity("Contact_Microservice.Entities.Contact", b =>
                {
                    b.HasOne("Contact_Microservice.Entities.Person", "Person")
                        .WithMany("Contacts")
                        .HasForeignKey("PersonUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Contact_Microservice.Entities.Person", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
