// <auto-generated />
using System;
using Contact_Microservice.DataAccess.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Contact_Microservice.Migrations
{
    [DbContext(typeof(PgDbContext))]
    partial class PgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Contact_Microservice.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContactType")
                        .HasColumnType("integer");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PersonUID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonUID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca32f3b0-3fe9-40ef-939f-14c9c403e8c0"),
                            ContactType = 3,
                            Contents = "antalya",
                            PersonUID = new Guid("e2f7b429-aa1d-4136-b412-523dce964993")
                        },
                        new
                        {
                            Id = new Guid("f7f4936f-a3d3-4c2e-8dd9-27e18d471218"),
                            ContactType = 1,
                            Contents = "05414414444",
                            PersonUID = new Guid("e2f7b429-aa1d-4136-b412-523dce964993")
                        },
                        new
                        {
                            Id = new Guid("896233ef-6883-4bcc-8210-1d8a0454ffba"),
                            ContactType = 3,
                            Contents = "antalya",
                            PersonUID = new Guid("0cb78979-5935-4793-be77-3aae7cdc7c4a")
                        },
                        new
                        {
                            Id = new Guid("d4bef437-2fd6-4d8a-bf86-d2d276c68139"),
                            ContactType = 1,
                            Contents = "05414414444",
                            PersonUID = new Guid("0cb78979-5935-4793-be77-3aae7cdc7c4a")
                        },
                        new
                        {
                            Id = new Guid("5a087447-cb5f-41f9-a621-29a39c499d84"),
                            ContactType = 1,
                            Contents = "05415555555",
                            PersonUID = new Guid("0cb78979-5935-4793-be77-3aae7cdc7c4a")
                        },
                        new
                        {
                            Id = new Guid("caa57e29-cde4-491f-b221-60a016e6de99"),
                            ContactType = 3,
                            Contents = "antalya",
                            PersonUID = new Guid("3874e9c0-8a55-49db-9c0f-88ce17372086")
                        },
                        new
                        {
                            Id = new Guid("fd5df557-6d12-48c1-9a93-fa195e14548a"),
                            ContactType = 1,
                            Contents = "05415552233",
                            PersonUID = new Guid("3874e9c0-8a55-49db-9c0f-88ce17372086")
                        },
                        new
                        {
                            Id = new Guid("a31aca8d-272f-4066-8f81-c6eb59af1705"),
                            ContactType = 3,
                            Contents = "izmir",
                            PersonUID = new Guid("24fb9dd1-9ca7-4bed-a95b-1dae06d4a4bb")
                        },
                        new
                        {
                            Id = new Guid("a27d7023-d9a5-4b7e-b1d3-b51b855cb0f3"),
                            ContactType = 1,
                            Contents = "05411112233",
                            PersonUID = new Guid("24fb9dd1-9ca7-4bed-a95b-1dae06d4a4bb")
                        },
                        new
                        {
                            Id = new Guid("16551247-f3b5-4418-aa90-c41d8759ee33"),
                            ContactType = 3,
                            Contents = "izmir",
                            PersonUID = new Guid("9f17228d-020a-4a38-a2d3-8793625f79a6")
                        },
                        new
                        {
                            Id = new Guid("7207209e-3af0-419b-813f-8508ad5c5147"),
                            ContactType = 1,
                            Contents = "05413332211",
                            PersonUID = new Guid("9f17228d-020a-4a38-a2d3-8793625f79a6")
                        },
                        new
                        {
                            Id = new Guid("39deb96f-c6d2-455a-9357-54084b384983"),
                            ContactType = 3,
                            Contents = "izmir",
                            PersonUID = new Guid("2b513153-af53-4257-926f-860cb14d6813")
                        },
                        new
                        {
                            Id = new Guid("b61022c3-0ad2-45d7-88e4-dd0ec68d44bd"),
                            ContactType = 3,
                            Contents = "urfa",
                            PersonUID = new Guid("c80cbe29-d732-4fae-b6c2-b73ad8334faf")
                        },
                        new
                        {
                            Id = new Guid("0dd5d6e5-1c40-4eff-8ff0-f35a82d83ac5"),
                            ContactType = 1,
                            Contents = "05417778899",
                            PersonUID = new Guid("c80cbe29-d732-4fae-b6c2-b73ad8334faf")
                        },
                        new
                        {
                            Id = new Guid("64253f97-69b0-4cd3-bcc4-378fbb0f4955"),
                            ContactType = 3,
                            Contents = "urfa",
                            PersonUID = new Guid("79a1e27a-629a-474e-bbcb-362274b65104")
                        },
                        new
                        {
                            Id = new Guid("af20dc4e-1d0c-4c56-9a97-779a25574acb"),
                            ContactType = 3,
                            Contents = "urfa",
                            PersonUID = new Guid("4e5a3699-ee36-444c-a203-50248a448d21")
                        });
                });

            modelBuilder.Entity("Contact_Microservice.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2f7b429-aa1d-4136-b412-523dce964993"),
                            Company = "Sanatcı a.ş",
                            Name = "Levent",
                            SurName = "Yüksel"
                        },
                        new
                        {
                            Id = new Guid("0cb78979-5935-4793-be77-3aae7cdc7c4a"),
                            Company = "Futbol a.ş",
                            Name = "Burak",
                            SurName = "Yılmaz"
                        },
                        new
                        {
                            Id = new Guid("3874e9c0-8a55-49db-9c0f-88ce17372086"),
                            Company = "Oyuncu a.ş",
                            Name = "Mehmet",
                            SurName = "Özgür"
                        },
                        new
                        {
                            Id = new Guid("24fb9dd1-9ca7-4bed-a95b-1dae06d4a4bb"),
                            Company = "Oyuncu a.ş",
                            Name = "Elçin",
                            SurName = "Sangu"
                        },
                        new
                        {
                            Id = new Guid("9f17228d-020a-4a38-a2d3-8793625f79a6"),
                            Company = "Oyuncu a.ş",
                            Name = "Selin",
                            SurName = "Şekerci"
                        },
                        new
                        {
                            Id = new Guid("2b513153-af53-4257-926f-860cb14d6813"),
                            Company = "Oyuncu a.ş",
                            Name = "Ece",
                            SurName = "Uslu"
                        },
                        new
                        {
                            Id = new Guid("c80cbe29-d732-4fae-b6c2-b73ad8334faf"),
                            Company = "Şarkıcı a.ş",
                            Name = "İbrahim",
                            SurName = "Tatlıses"
                        },
                        new
                        {
                            Id = new Guid("79a1e27a-629a-474e-bbcb-362274b65104"),
                            Company = "Şarkıcı a.ş",
                            Name = "Müslüm",
                            SurName = "Gürses"
                        },
                        new
                        {
                            Id = new Guid("4e5a3699-ee36-444c-a203-50248a448d21"),
                            Company = "Şarkıcı a.ş",
                            Name = "Mahmut",
                            SurName = "Tuncer"
                        });
                });

            modelBuilder.Entity("Contact_Microservice.Entities.Contact", b =>
                {
                    b.HasOne("Contact_Microservice.Entities.Person", "Person")
                        .WithMany("Contacts")
                        .HasForeignKey("PersonUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Contact_Microservice.Entities.Person", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
